enable:
disable:
restore_lights:
  fields:
    lights:
      selector:
        entity:
          domain: light
          multiple: true
override_lights:
  fields:
    lights:
      required: true
      selector:
        entity:
          domain: light
          multiple: true
    brightness:
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
    color_temp:
      selector:
        color_temp:
          unit: kelvin
          min: 2000
          max: 6500
    rgb_color:
      selector:
        color_rgb:
